# Runs hdWGCNA on every cell type in every tissue, using
# 17_obj_reassembly.R's final per-tissue objects as the source. Runs as a
# SLURM job array (see jobs/wgcna_single.sh), one task per row of
# jobs/wgcna_single_params.txt -- a full enumeration of every distinct
# cell_type3 value in each tissue, generated by
# wgcna_single_params.R (not hand-curated, since the request here is
# literally "every cell type from every tissue", unlike 13/15/19's
# deliberately-selected subsets).
#
# Reworked from the user's pushed draft (a copy-paste from the earlier
# als_multitissue_scfrp/sea_ad_hypothalamus projects). Design notes:
# - commandArgs()-based argument passing replaced with this project's
#   established SLURM_ARRAY_TASK_ID + params-file fail-fast pattern
#   (matching 13/14's use of jobs/13_params.txt).
# - The draft's load("/projects/b1169/projects/sea_ad_hypothalamus/.../
#   helperfunctions.RData") pointed at a completely different,
#   inaccessible project, and nothing later in the script calls an
#   unrecognized function from it -- dropped rather than carried forward.
#   Flag if something in hdWGCNA/hdWGCNA's ecosystem *was* silently
#   depending on it (unlikely -- nothing else in the draft used a
#   non-package function).
# - Loads the whole tissue's cleaned, annotated object from
#   17_obj_reassembly.R. Real raw counts come from
#   data/06_obj_reassembly/bpcells (17's own saved bpcells_data holds
#   normalized data, not counts -- the usual pipeline-wide gotcha, and
#   MetacellsByGroups() below specifically needs to sum real counts to
#   build metacells), plus a fresh NormalizeData(). 17's own already-fit
#   data/17_obj_reassembly/<tissue>/harmony.rds is reattached directly
#   rather than refit -- unlike 13/15/19, this script doesn't need a
#   subset-specific integration: metacells are built by KNN within the
#   whole tissue's existing embedding, then restricted to the target cell
#   type via MetacellsByGroups()/SetDatExpr()'s own group.by/group_name
#   arguments, matching the draft's own approach of running
#   SetupForWGCNA() on the full tissue object rather than a subset.
# - The draft's PredictedCellType/sample_ID/Batch/Group2 column aliasing
#   is replaced with this project's actual column names (cell_type3,
#   orig.ident, batch, group) throughout.
# - SetDatExpr()'s draft argument was `slot = "data"` (Seurat v4 naming);
#   hdWGCNA's current version supports `layer =` for Seurat v5 (confirmed
#   against hdWGCNA's own docs, not guessed) -- updated to
#   `layer = "data"`, matching this project's exclusive use of Seurat v5
#   layer= terminology everywhere else.
# - Skips (fails fast with a clear message, before attempting the
#   pipeline) any (cell_type, tissue) combination with fewer than
#   min_cells cells -- metacell construction (k = 25 nearest neighbors)
#   needs a reasonable population to produce stable, non-degenerate
#   metacells. This project already hit an analogous "too few cells
#   breaks the pipeline" issue with pseudobulk DESeq2 (deseq2.R); the same
#   lesson is applied here proactively instead of waiting to hit it.
# - Saves the decomposed hdWGCNA outputs (module table, harmonized module
#   eigengenes, smoothed UCell module scores, soft-power table, plots) as
#   plain CSVs/PNGs under results/wgcna_single/<tissue>/<cell_type>/,
#   matching this project's usual results/ convention. One deliberate
#   exception to "never a whole-object saveRDS()": hdWGCNA's own function
#   ecosystem expects a Seurat object carrying its network/TOM/module
#   state in @misc[[wgcna_name]] to resume further hdWGCNA-specific
#   analysis later. Rather than saveRDS()-ing the entire tissue-scale
#   object (which would duplicate the whole single-cell expression
#   matrix -- already saved separately by 17_obj_reassembly.R -- once per
#   cell type), only that @misc[[wgcna_name]] hdWGCNA experiment list is
#   saved, to data/wgcna_single/<tissue>/<cell_type>/wgcna_experiment.rds
#   -- a compact, self-contained artifact hdWGCNA can reattach to a fresh
#   Seurat object if needed.

suppressMessages({
  library(hdWGCNA)
  library(Seurat)
  library(scCustomize)
  library(tidyverse)
  library(patchwork)
  library(UCell)
  library(cowplot)
  library(BPCells)
})

message2 <- function(text){
  v1 <- paste(rep("~", 15),
              collapse = "")
  message(paste0(v1, text, v1))
}

setwd("/projects/b1169/boles/als_cns_scrnaseq")

theme_set(theme_cowplot())
set.seed(256)
enableWGCNAThreads(nThreads = 16)

# Figure out which (cell_type, tissue) combination this task handles ------
# jobs/wgcna_single_params.txt is generated by wgcna_single_params.R (a
# full enumeration of every cell_type3 value per tissue) -- regenerate it
# and update jobs/wgcna_single.sh's --array range if 17_obj_reassembly.R's
# output or annotations change.

params <- read.csv("jobs/wgcna_single_params.txt", header = F,
                   col.names = c("cell_type", "tissue_file"))

task_id <- Sys.getenv("SLURM_ARRAY_TASK_ID")
if (task_id == ""){
  stop("SLURM_ARRAY_TASK_ID is not set -- this script is meant to run as a ",
       "SLURM job array (see jobs/wgcna_single.sh), one task per row of ",
       "jobs/wgcna_single_params.txt, not as a standalone Rscript call.")
}
task_id <- as.integer(task_id)

if (task_id < 1 | task_id > nrow(params)){
  stop(paste0("SLURM_ARRAY_TASK_ID (", task_id, ") is out of range for ",
              nrow(params), " (cell_type, tissue) combinations in ",
              "jobs/wgcna_single_params.txt -- check the --array range in ",
              "jobs/wgcna_single.sh."))
}

cell_type_target <- params$cell_type[task_id]
tissue_file <- params$tissue_file[task_id]
file <- str_replace_all(cell_type_target, " ", "_")

message2(paste0("Processing ", cell_type_target, " (", tissue_file,
                "), task ", task_id, "/", nrow(params)))

data_dir <- paste0("data/wgcna_single/", tissue_file, "/", file, "/")
dir.create(data_dir, showWarnings = F, recursive = T)

results_dir <- paste0("results/wgcna_single/", tissue_file, "/", file, "/")
dir.create(results_dir, showWarnings = F, recursive = T)

# Load the tissue object from 17_obj_reassembly.R ----------------------------

message2("Reading in metadata, raw counts, and Harmony embedding")

meta <- readRDS(paste0("data/17_obj_reassembly/", tissue_file, "/metadata.rds"))

raw_mat <- open_matrix_dir("data/06_obj_reassembly/bpcells")
raw_mat <- raw_mat[, rownames(meta)]

obj <- CreateSeuratObject(counts = raw_mat, meta.data = meta, assay = "RNA")
obj <- NormalizeData(obj)

harmony <- readRDS(paste0("data/17_obj_reassembly/", tissue_file, "/harmony.rds"))
obj[["harmony"]] <- harmony

# Skip cell types too sparsely represented for stable metacell construction -
# See header note above.

min_cells <- 200 # change as needed

n_cells <- sum(obj$cell_type3 == cell_type_target)
if (n_cells < min_cells){
  stop(paste0(cell_type_target, " (", tissue_file, ") has only ", n_cells,
              " cells, below min_cells = ", min_cells, " -- too few for ",
              "stable metacell construction. Adjust min_cells in this ",
              "script if this cutoff is too strict."))
}

obj <- ScaleData(obj)

# Identify genes expressed in at least 5% of this cell type's cells ---------

message2("Selecting genes expressed in at least 5% of this cell type")

sub <- subset(obj, cell_type3 == cell_type_target)

pe <- rowMeans(GetAssayData(sub, layer = "data", assay = "RNA") > 0)
genes_keep <- names(pe)[pe > 0.05] # change this cutoff as needed

# Set up hdWGCNA on the whole tissue object -----------------------------
# Matches the draft's own approach -- metacells are built by KNN within
# the whole tissue's existing Harmony embedding, then restricted to this
# cell type via MetacellsByGroups()/SetDatExpr()'s group.by/group_name
# arguments (see header note above), not by subsetting obj itself.

message2("Setting up hdWGCNA")

obj <- SetupForWGCNA(obj,
                     gene_select = "custom",
                     features = genes_keep,
                     wgcna_name = file)

message2("Constructing metacells")

obj <- MetacellsByGroups(
  seurat_obj = obj,
  group.by = c("cell_type3", "orig.ident"),
  reduction = "harmony",
  k = 25, # change as needed
  max_shared = 10, # change as needed
  ident.group = "cell_type3"
)

obj <- NormalizeMetacells(obj)
obj <- ScaleMetacells(obj, features = VariableFeatures(obj))
obj <- RunPCAMetacells(obj, features = VariableFeatures(obj))
obj <- RunHarmonyMetacells(obj, group.by.vars = "orig.ident")

obj <- SetDatExpr(
  obj,
  group_name = cell_type_target,
  group.by = "cell_type3",
  assay = "RNA",
  layer = "data",
  use_metacells = T
)

# Find soft power ---------------------------------------------------------

message2("Testing soft powers")

obj <- TestSoftPowers(obj)

plot_list <- PlotSoftPowers(obj)
p <- wrap_plots(plot_list, ncol = 2)
ggsave(p,
       filename = paste0(results_dir, "soft_power.png"),
       units = "in", dpi = 600,
       height = 8, width = 8)

power_table <- GetPowerTable(obj)
write.csv(power_table,
          file = paste0(results_dir, "soft_powers.csv"),
          row.names = F)

# Build TOM and cluster genes into modules -----------------------------------
# Letting ConstructNetwork() pick the soft power automatically, matching
# the draft.

message2("Constructing network")

obj <- ConstructNetwork(obj,
                        tom_name = file,
                        overwrite_tom = T)

png(paste0(results_dir, "dendrogram.png"),
    height = 8, width = 8, units = "in", res = 600)
PlotDendrogram(obj, main = paste0(cell_type_target, " dendrogram"))
dev.off()

# Module stats ------------------------------------------------------------

message2("Computing module eigengenes and connectivity")

obj <- SetActiveWGCNA(obj, file)
obj <- ModuleEigengenes(obj, group.by.vars = "orig.ident")
obj <- ModuleConnectivity(obj, group_name = cell_type_target, group.by = "cell_type3")

p <- PlotKMEs(obj, ncol = 4, text_size = 4)
ggsave(p,
       filename = paste0(results_dir, "module_connectivity.png"),
       units = "in", dpi = 600,
       height = 12, width = 12)

mods <- obj@misc[[file]][["wgcna_modules"]]
write.csv(mods,
          file = paste0(results_dir, "modules.csv"),
          row.names = F)

# Module expression scores via UCell -----------------------------------------

message2("Scoring modules with UCell")

module_names <- setdiff(unique(mods$module), "grey")

gene_sets <- lapply(module_names, function(m){
  mods$gene_name[mods$module == m]
})
names(gene_sets) <- module_names

maxrank <- max(lengths(gene_sets))

sub <- subset(obj, cell_type3 == cell_type_target)
sub <- AddModuleScore_UCell(sub, features = gene_sets, maxRank = maxrank)
sub <- SmoothKNN(sub,
                 signature.names = paste0(names(gene_sets), "_UCell"),
                 reduction = "harmony")

scores <- sub@meta.data %>%
  dplyr::select(orig.ident, group, matches("_UCell_kNN$"))

write.csv(scores,
          file = paste0(results_dir, "module_scores_ucell.csv"),
          row.names = F)

# Harmonized module eigengenes -----------------------------------------------

message2("Saving module eigengenes")

hMEs <- GetMEs(obj, harmonized = T)
write.csv(hMEs,
          file = paste0(results_dir, "module_eigengenes.csv"))

png(paste0(results_dir, "module_eigengene_correlogram.png"),
    height = 8, width = 8, units = "in", res = 600)
ModuleCorrelogram(obj, features = "MEs")
dev.off()

# Save the hdWGCNA experiment for further downstream use ---------------------
# Just the hdWGCNA network/module state (@misc[[wgcna_name]]), not the
# whole tissue-scale Seurat object -- see header note above.

message2("Saving hdWGCNA experiment object")

wgcna_experiment <- obj@misc[[file]]
saveRDS(wgcna_experiment,
        file = paste0(data_dir, "wgcna_experiment.rds"))
