# Runs hdWGCNA on every cell type in every tissue, using
# 17_obj_reassembly.R's final per-tissue objects as the source: filters
# to one cell type's cells before touching raw counts, builds metacells,
# constructs the co-expression network, and scores modules per cell.
# Saves module tables, harmonized module eigengenes, smoothed UCell
# module scores, and soft-power/network diagnostics. Runs as a SLURM job
# array (see jobs/wgcna_single.sh), one task per row of
# jobs/wgcna_single_params.txt (every cell type in every tissue).

suppressMessages({
  library(hdWGCNA)
  library(Seurat)
  library(scCustomize)
  library(tidyverse)
  library(patchwork)
  library(UCell)
  library(cowplot)
  library(BPCells)
})

message2 <- function(text){
  v1 <- paste(rep("~", 15),
              collapse = "")
  message(paste0(v1, text, v1))
}

project_root <- "/projects/b1169/boles/als_cns_scrnaseq"
setwd(project_root)

theme_set(theme_cowplot())
set.seed(256)
enableWGCNAThreads(nThreads = 16)

# Figure out which (cell_type, tissue) combination this task handles ------
# jobs/wgcna_single_params.txt is generated by wgcna_single_params.R (a
# full enumeration of every cell_type3 value per tissue) -- regenerate it
# and update jobs/wgcna_single.sh's --array range if 17_obj_reassembly.R's
# output or annotations change.

params <- read.csv("jobs/wgcna_single_params.txt", header = F,
                   col.names = c("cell_type", "tissue_file"))

task_id <- Sys.getenv("SLURM_ARRAY_TASK_ID")
if (task_id == ""){
  stop("SLURM_ARRAY_TASK_ID is not set -- this script is meant to run as a ",
       "SLURM job array (see jobs/wgcna_single.sh), one task per row of ",
       "jobs/wgcna_single_params.txt, not as a standalone Rscript call.")
}
task_id <- as.integer(task_id)

if (task_id < 1 | task_id > nrow(params)){
  stop(paste0("SLURM_ARRAY_TASK_ID (", task_id, ") is out of range for ",
              nrow(params), " (cell_type, tissue) combinations in ",
              "jobs/wgcna_single_params.txt -- check the --array range in ",
              "jobs/wgcna_single.sh."))
}

cell_type_target <- params$cell_type[task_id]
tissue_file <- params$tissue_file[task_id]
file <- str_replace_all(cell_type_target, " ", "_")

message2(paste0("Processing ", cell_type_target, " (", tissue_file,
                "), task ", task_id, "/", nrow(params)))

# Absolute paths, unlike every other script's relative results_dir/
# data_dir -- this script is the only one that temporarily setwd()s
# elsewhere mid-run (see the ConstructNetwork() TOM-collision workaround
# below), so a relative path here could silently resolve against the
# wrong directory if anything ever reads/writes results_dir or data_dir
# from inside that block.

data_dir <- paste0(project_root, "/data/wgcna_single/", tissue_file, "/", file, "/")
dir.create(data_dir, showWarnings = F, recursive = T)

results_dir <- paste0(project_root, "/results/wgcna_single/", tissue_file, "/", file, "/")
dir.create(results_dir, showWarnings = F, recursive = T)

# Filter to this cell type before touching raw counts at all ----------------
# See header note above -- filtering the metadata first means raw_mat is
# opened already subset to just this cell type's barcodes, and nothing
# downstream ever processes the tissue's other cell types.

message2("Reading in metadata and filtering to this cell type")

meta <- readRDS(paste0("data/17_obj_reassembly/", tissue_file, "/metadata.rds"))
meta_sub <- meta[meta$cell_type3 == cell_type_target, ]

# Skip cell types too sparsely represented for stable metacell construction -
# Checked here, before loading raw counts, so an under-abundant cell type
# fails fast and cheaply.

min_cells <- 200 # change as needed

if (nrow(meta_sub) < min_cells){
  stop(paste0(cell_type_target, " (", tissue_file, ") has only ",
              nrow(meta_sub), " cells, below min_cells = ", min_cells,
              " -- too few for stable metacell construction. Adjust ",
              "min_cells in this script if this cutoff is too strict."))
}

message2("Reading in raw counts and Harmony embedding")

raw_mat <- open_matrix_dir("data/06_obj_reassembly/bpcells")
raw_mat <- raw_mat[, rownames(meta_sub)]

obj <- CreateSeuratObject(counts = raw_mat, meta.data = meta_sub, assay = "RNA")
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)

harmony <- readRDS(paste0("data/17_obj_reassembly/", tissue_file, "/harmony.rds"))
harmony@cell.embeddings <- harmony@cell.embeddings[rownames(meta_sub), ]
obj[["harmony"]] <- harmony

obj <- ScaleData(obj)

# Identify genes expressed in at least 5% of this cell type's cells ---------

message2("Selecting genes expressed in at least 5% of this cell type")

pe <- rowMeans(GetAssayData(obj, layer = "data", assay = "RNA") > 0)
genes_keep <- names(pe)[pe > 0.05] # change this cutoff as needed

# Set up hdWGCNA -------------------------------------------------------
# obj is already filtered to just this cell type -- see header note above.

message2("Setting up hdWGCNA")

obj <- SetupForWGCNA(obj,
                     gene_select = "custom",
                     features = genes_keep,
                     wgcna_name = file)

message2("Constructing metacells")

# group.by is just orig.ident now (not c("cell_type3", "orig.ident") as
# in the draft/tutorial) -- cell_type3 is constant across obj at this
# point, so grouping by it too would be a no-op.
obj <- MetacellsByGroups(
  seurat_obj = obj,
  group.by = c("orig.ident", "cell_type3"),
  reduction = "harmony",
  k = 25, # change as needed
  max_shared = 10, # change as needed
  ident.group = "cell_type3"
)

obj <- NormalizeMetacells(obj)
obj <- ScaleMetacells(obj, features = VariableFeatures(obj))
obj <- RunPCAMetacells(obj, features = VariableFeatures(obj))
obj <- RunHarmonyMetacells(obj, group.by.vars = "orig.ident")

obj <- SetDatExpr(
  obj,
  group_name = cell_type_target,
  group.by = "cell_type3",
  assay = "RNA",
  layer = "data",
  use_metacells = T
)

# Find soft power ---------------------------------------------------------

message2("Testing soft powers")

obj <- TestSoftPowers(obj)

plot_list <- PlotSoftPowers(obj)
p <- wrap_plots(plot_list, ncol = 2)
ggsave(p,
       filename = paste0(results_dir, "soft_power.png"),
       units = "in", dpi = 600,
       height = 8, width = 8)

power_table <- GetPowerTable(obj)
write.csv(power_table,
          file = paste0(results_dir, "soft_powers.csv"),
          row.names = F)

# Build TOM and cluster genes into modules -----------------------------------
# Letting ConstructNetwork() pick the soft power automatically, matching
# the draft.
#
# ConstructNetwork() (via WGCNA::blockwiseConsensusModules() underneath)
# writes a temporary .rda file to the current working directory -- not to
# tom_outdir, and not prefixed by tom_name -- a known, unfixed hdWGCNA bug
# (smorabit/hdWGCNA#182). Every task in this script shares one setwd() to
# the project root, so parallel array tasks collide on that same generic
# temp filename regardless of how unique tom_name is -- this is the
# SLURM-array TOM.rda collision. Workaround (matching what other hdWGCNA
# users on SLURM clusters have landed on, per that issue): give this task
# its own working directory for just this call, so whatever literal
# filename WGCNA writes internally lands in a physically separate folder.
# tom_outdir defaults to a "TOM" subfolder of the working directory, so
# this also isolates the actual named TOM output per task as a side
# effect, not just the stray temp file.

message2("Constructing network")

tom_dir <- paste0(data_dir, "tom/")
dir.create(tom_dir, showWarnings = F, recursive = T)

setwd(tom_dir)
tryCatch({
  obj <- ConstructNetwork(obj,
                          tom_name = file,
                          overwrite_tom = T)
}, finally = {
  setwd(project_root)
})

png(paste0(results_dir, "dendrogram.png"),
    height = 8, width = 8, units = "in", res = 600)
PlotDendrogram(obj, main = paste0(cell_type_target, " dendrogram"))
dev.off()

# Module stats ------------------------------------------------------------

message2("Computing module eigengenes and connectivity")

obj <- SetActiveWGCNA(obj, file)
obj <- ModuleEigengenes(obj, group.by.vars = "orig.ident")

# ModuleConnectivity() (unlike everything before it) reaches back into
# the full single-cell "data" layer for its corSparse()-based
# correlation step, which needs a real CsparseMatrix -- BPCells' lazy
# matrix classes (e.g. "RenameDims", produced internally by dimname/
# subsetting operations) don't implement that coercion, and hdWGCNA has
# no awareness it might be handed a BPCells-backed layer at all, so this
# fails with "no method or default for coercing 'RenameDims' to
# 'CsparseMatrix'" if left BPCells-backed. Same class of gotcha as this
# project's IntegrateLayers()/CCA history (see CLAUDE.md). Materializing
# only right here, not earlier (e.g. right after NormalizeData()), lets
# gene selection, SetupForWGCNA(), and metacell construction above keep
# running on the BPCells-backed layer and its usual streaming/lazy
# efficiency -- nothing before this line actually needs a real
# CsparseMatrix.
obj[["RNA"]]$data <- as(obj[["RNA"]]$data, "dgCMatrix")

obj <- ModuleConnectivity(obj, group_name = cell_type_target, group.by = "cell_type3")

p <- PlotKMEs(obj, ncol = 4, text_size = 4)
ggsave(p,
       filename = paste0(results_dir, "module_connectivity.png"),
       units = "in", dpi = 600,
       height = 12, width = 12)

mods <- obj@misc[[file]][["wgcna_modules"]]
write.csv(mods,
          file = paste0(results_dir, "modules.csv"),
          row.names = F)

# Module expression scores via UCell -----------------------------------------

message2("Scoring modules with UCell")

module_names <- setdiff(unique(mods$module), "grey")

gene_sets <- lapply(module_names, function(m){
  mods$gene_name[mods$module == m]
})
names(gene_sets) <- module_names

maxrank <- max(lengths(gene_sets))

# No subset needed here (unlike the draft) -- obj already contains only
# this cell type's cells.
obj <- AddModuleScore_UCell(obj, features = gene_sets, maxRank = maxrank)
obj <- SmoothKNN(obj,
                 signature.names = paste0(names(gene_sets), "_UCell"),
                 reduction = "harmony")

scores <- obj@meta.data %>%
  dplyr::select(orig.ident, group, matches("_UCell_kNN$"))

write.csv(scores,
          file = paste0(results_dir, "module_scores_ucell.csv"),
          row.names = F)

# Harmonized module eigengenes -----------------------------------------------

message2("Saving module eigengenes")

hMEs <- GetMEs(obj, harmonized = T)
write.csv(hMEs,
          file = paste0(results_dir, "module_eigengenes.csv"))

png(paste0(results_dir, "module_eigengene_correlogram.png"),
    height = 8, width = 8, units = "in", res = 600)
ModuleCorrelogram(obj, features = "MEs")
dev.off()

# Save the hdWGCNA experiment for further downstream use ---------------------
# Just the hdWGCNA network/module state (@misc[[wgcna_name]]), not the
# whole tissue-scale Seurat object -- see header note above.

message2("Saving hdWGCNA experiment object")

wgcna_experiment <- obj@misc[[file]]
saveRDS(wgcna_experiment,
        file = paste0(data_dir, "wgcna_experiment.rds"))
